/**
 * Lankheet Domotics api
 * Lankheet Domotics API
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DomiotParameterModel {
    /**
     * unique identification
     */
    readonly id?: number;
    name?: string;
    parameterType?: DomiotParameter.ParameterTypeEnum;
    value?: object;
    readonly?: boolean;
}
export namespace DomiotParameter {
    export type ParameterTypeEnum = 'String' | 'Number' | 'Boolean';
    export const ParameterTypeEnum = {
        String: 'String' as ParameterTypeEnum,
        Number: 'Number' as ParameterTypeEnum,
        Boolean: 'Boolean' as ParameterTypeEnum
    };
}


