/**
 * Lankheet Domotics api
 * Lankheet Domotics API
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The configured topics for the local mqtt broker
 */
export interface MqttTopicModel {
    /**
     * unique identification
     */
    readonly id?: number;
    /**
     * the mqtt topic path e.g. home1/0/fusebox/p1/pact1
     */
    path?: string;
}

