/**
 * Lankheet Domotics api
 * Lankheet Domotics API
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sensor types; the first entry is for making the first one start with ordinal 1
 */
export type SensorTypeModel = 'NOT_USED' | 'POWER_PT1' | 'POWER_PT2' | 'POWER_CT1' | 'POWER_CT2' | 'POWER_AC' | 'POWER_AP' | 'GAS_METER' | 'TEMP' | 'HUMID' | 'WATER' | 'GAS_SENSOR' | 'HYDRO' | 'STATUS' | 'VOLTAGE_LEVEL' | 'CURRENT_LEVEL';

export const SensorType = {
    NotUsed: 'NOT_USED' as SensorTypeModel,
    PowerPt1: 'POWER_PT1' as SensorTypeModel,
    PowerPt2: 'POWER_PT2' as SensorTypeModel,
    PowerCt1: 'POWER_CT1' as SensorTypeModel,
    PowerCt2: 'POWER_CT2' as SensorTypeModel,
    PowerAc: 'POWER_AC' as SensorTypeModel,
    PowerAp: 'POWER_AP' as SensorTypeModel,
    GasMeter: 'GAS_METER' as SensorTypeModel,
    Temp: 'TEMP' as SensorTypeModel,
    Humid: 'HUMID' as SensorTypeModel,
    Water: 'WATER' as SensorTypeModel,
    GasSensor: 'GAS_SENSOR' as SensorTypeModel,
    Hydro: 'HYDRO' as SensorTypeModel,
    Status: 'STATUS' as SensorTypeModel,
    VoltageLevel: 'VOLTAGE_LEVEL' as SensorTypeModel,
    CurrentLevel: 'CURRENT_LEVEL' as SensorTypeModel
};

